### ISSUE TITLE
java.lang.NullPointerException on failed tests

### ISSUE THREAD

**Issue by amai2012** [jenkinsci/junit-plugin#434] opened 2022-09-21 13:55 UTC
### Jenkins and plugins versions report

Recent plugin(!) updates seem to have caused this

Versions:
- Jenkins 2.361.1 (also LTS before - which is the reason I think the plugin updates caused it)
- junit  1119.1121.vc43d0fc45561
- claim 495.v01a_c6fb_2b_a_7a

### What Operating System are you using (both controller, and any agents involved in the problem)?

jenkins master SLES 12
slave - any, e.g. Windows 2019 server

### Reproduction steps

- run build job with failed tests
- claim from declarative pipeline

### Expected Results

No exception

### Actual Results

`15:43:33  Recording test results
15:43:34  null
Error when executing always post condition:
java.lang.NullPointerException
	at hudson.plugins.claim.AbstractClaimBuildAction.<init>(AbstractClaimBuildAction.java:39)
	at hudson.plugins.claim.ClaimTestAction.<init>(ClaimTestAction.java:18)
	at hudson.plugins.claim.ClaimTestDataPublisher$Data.getTestAction(ClaimTestDataPublisher.java:117)
	at hudson.tasks.junit.TestResultAction.getActions(TestResultAction.java:253)
	at hudson.tasks.test.TestObject.getTestActions(TestObject.java:254)
	at hudson.tasks.test.TestObject.getTestAction(TestObject.java:267)
	at hudson.plugins.claim.ClaimTestDataPublisher.contributeTestData(ClaimTestDataPublisher.java:41)
	at hudson.plugins.claim.ClaimTestDataPublisher.contributeTestData(ClaimTestDataPublisher.java:22)
	at hudson.tasks.junit.JUnitResultArchiver.parseAndSummarize(JUnitResultArchiver.java:291)
	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:63)
	at hudson.tasks.junit.pipeline.JUnitResultsStepExecution.run(JUnitResultsStepExecution.java:29)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)`

### Anything else?

Recent plugin(!) updates seem to have caused this

Versions:
- Jenkins 2.361.1 (also LTS before - which is the reason I think the plugin updates caused it)
- junit  1119.1121.vc43d0fc45561
- claim 495.v01a_c6fb_2b_a_7a

**Comment by amai2012** [comment] 2022-09-21 14:51
> The null pointer is in the claim plugin have you reported it there first?
> 
> The JUnit plugin has barely changed since May

Ok, here we are: https://issues.jenkins.io/browse/JENKINS-69664

**Comment by timja** [comment] 2022-09-21 14:58
Thanks will close this for now as unlikely to be caused by this plugin

**Closed as not planned by timja** 2022-09-21 14:58 UTC
